name: Build OpenSSL on Windows

on:
  workflow_dispatch:  # 手动触发工作流

jobs:
  build:
    runs-on: windows-latest
    env:
      MSYS2_PATH_TYPE: inherit  # 保持MSYS2路径

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up MSYS2
      run: |
        choco install msys2
        C:\msys64\usr\bin\bash.exe -l -c "pacman -Syu --noconfirm"

    - name: Install mingw-w64-x86_64-toolchain, gcc, perl
      run: |
        C:\msys64\usr\bin\bash.exe -l -c "pacman -S --noconfirm mingw-w64-x86_64-toolchain gcc perl"

    - name: Build OpenSSL
      run: |
        # 进入 OpenSSL 目录
        C:\msys64\usr\bin\bash.exe -l -c "
          cd openssl/openssl-3.1
          perl Configure mingw64 --prefix=\$PWD/opt
          make
          make install
        "

    - name: Upload opt directory as artifact
      uses: actions/upload-artifact@v3
      with:
        name: openssl-opt
        path: ./openssl/openssl-3.1/opt  # 上传 opt 目录的内容
